name: Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: "3.11"
      - uses: actions/configure-pages@v5
      - run: uv sync --locked
      - run: uv run --with pdoc pdoc ./src/neo_monitor -o docs/api
      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs/api

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
